version: "3.8"
services:
    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: aspnetcore
            MYSQL_USER: aspnetcore
            MYSQL_PASSWORD: 123456
        volumes:
            - ./mysql_data:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: 123456
        ports:
            - 8080:80

    gamestore:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:8080
        depends_on:
            - db
        environment:
            ConnectionStrings__DefaultConnection: "server=db;port=3306;database=aspnetcore;user=root;password=123456"
